name: ruang_tenang_mobile
description: "Ruang Tenang - Platform Kesehatan Mental"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.3.1
  fl_chart: ^0.70.2
  flutter_html: ^3.0.0-beta.2

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Routing
  go_router: ^14.8.1

  # Network
  dio: ^5.8.0+1

  # Dependency Injection
  get_it: ^8.0.3

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  hive_flutter: ^1.1.0

  # Form & Validation
  image_picker: ^1.1.2

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.2
  share_plus: ^10.1.4
  package_info_plus: ^8.3.0
  permission_handler: ^11.4.0
  connectivity_plus: ^6.1.4

  # Notifications
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^18.0.1

  # Media
  just_audio: ^0.10.5
  audio_service: ^0.18.18
  audio_session: ^0.1.25
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/moods/
    - assets/images/illustrations/
    - assets/images/onboarding/
    - assets/icons/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-VariableFont.ttf
